"""Port of buildEyeReport.js — Eye analysis Markdown report builder."""

from __future__ import annotations
from typing import Optional

from .answer_summary import format_answers_summary


def build_eye_report(eye_analysis: Optional[dict], answers: Optional[dict] = None) -> str:
    """Build a Markdown report from eye analysis results.

    Args:
        eye_analysis: Full eye analysis dict with 'metrics' key.
        answers: Optional user questionnaire answers.

    Returns:
        Markdown string of the eye report.
    """
    if answers is None:
        answers = {}

    metrics = (eye_analysis or {}).get("metrics")
    if not metrics:
        return "## Eye Analysis\n\nNo eye data available."

    profile = format_answers_summary(answers)
    goals = profile.get("goals", "not specified")

    return f"""## An overview of your eyes

*Computer vision analysis — MediaPipe landmarks + OpenCV-style color sampling. No LLM used.*

### Summary of your eyes

| Metric | Result |
|--------|--------|
| **Eye tilt** | {metrics.get('eyeTilt', 'N/A')} |
| **Eyelid exposure** | {metrics.get('eyelidExposure', 'N/A')} |
| **Sclera color** | {metrics.get('scleraColor', 'N/A')} |
| **Under-eye health** | {metrics.get('underEyeHealth', 'N/A')} |

### Lower eyelid curvature

- **Total bending (k):** {metrics.get('lowerLidCurvature', 'N/A')}
- **Typical range:** {metrics.get('curvatureMin', 'N/A')} – {metrics.get('curvatureMax', 'N/A')}
- **Assessment:** {metrics.get('curvatureDescription', 'N/A')}

Left eye tilt: {metrics.get('leftTilt', 'N/A')}° · Right eye tilt: {metrics.get('rightTilt', 'N/A')}° · Exposure ratio: {metrics.get('exposureRatio', 'N/A')}

### Explanation

{metrics.get('explanation', '')}

---

## Personalized note

Based on your goals (*{goals}*), focus on periorbital care: SPF around the eyes, gentle caffeine or peptide serums for under-eye area, and consistent sleep to support sclera clarity.

*Report generated by MyFace · Free CV path (MediaPipe + OpenCV) · $0 API cost*
"""
