import { computeMetrics } from './constants'
import { formatAnswersSummary } from './onboarding'

export function buildMockReport(answers, awsMetrics = null) {
  const metrics = awsMetrics?.source === 'aws' ? awsMetrics : computeMetrics(answers)
  const { goals, concerns, severity, occupation, smoking, medicalConditions, age, gender } = formatAnswersSummary(answers)

  const skinNote =
    answers.skinConcerns?.length > 0
      ? `Your selected concerns (${concerns}) are weighted at *${severity}* severity in this assessment.`
      : 'General skin quality assessment applied across all zones.'

  const genderRef = answers.gender === 'male' ? 'male' : answers.gender === 'female' ? 'female' : 'neutral'

  return `## Executive Summary

Your facial analysis reveals a **harmonious overall structure** with a composite harmony score of **${metrics.harmonyScore}/100**. Based on your goals (*${goals}*) and profile (${age}, ${gender}), we've tailored this assessment to your unique needs.

Your face demonstrates **above-average symmetry (${metrics.symmetry}%)** and solid proportional balance across vertical thirds — upper (${metrics.upperThird}), middle (${metrics.middleThird}), and lower (${metrics.lowerThird}).

${skinNote}

---

## Structural Analysis

### Facial Proportions
Your vertical facial thirds show a well-balanced distribution. The middle third sits slightly within the ideal range for your demographic cohort, contributing to a cohesive midface appearance. Horizontal fifths align closely with population norms, indicating natural facial width harmony.

### Symmetry Index: ${metrics.symmetry}%
Mild asymmetry is present — as with 97% of individuals — primarily in the periorbital region. This is within normal variation and does not require correction. Your left-right jaw alignment scores consistently.

### Jawline & Lower Face
- **Gonial angle:** ${metrics.jawlineAngle}° — within the ${genderRef} ideal range
- **Chin projection:** Balanced relative to nasal tip
- **Definition:** Moderate-to-good; enhancement possible through non-invasive methods

### Periorbital Region
- **Canthal tilt:** +${metrics.canthalTilt}° (slightly positive — associated with alertness)
- **Eyebrow tilt:** ${metrics.eyebrowTilt}°
- **Under-eye area:** Mild shadowing detected; responsive to topical brightening agents

### Nose & Midface
- **Nasolabial angle:** ${metrics.nasalAngle}°
- Bridge width proportional to intercanthal distance
- Tip rotation within expected range for your profile

---

## Skin & Surface Quality

Surface analysis indicates **moderate pore visibility** in the T-zone with otherwise even tone distribution. Estimated visual age: **${metrics.visualAge} years** — aligned with chronological expectations for your ${age} age group.

Priority focus areas: ${concerns}.

**Lifestyle context:** ${occupation} · Smoking: ${smoking} · Medical conditions: ${medicalConditions}.

---

## Top Strengths

1. **Facial symmetry** — Your ${metrics.symmetry}% symmetry score places you above the population median
2. **Proportional harmony** — Vertical thirds and horizontal fifths show natural balance
3. **Periorbital structure** — Positive canthal tilt contributes to an approachable, alert appearance

---

## Areas with Highest Improvement Potential

1. **Under-eye clarity** — Topical peptides + caffeine serums (4–8 weeks)
2. **Jawline definition** — Gua sha + posture correction + optional facial exercises
3. **Skin texture refinement** — Gentle retinoid introduction (if medically appropriate)

---

## Personalized 30-Day Protocol

*Aligned with your goals: ${goals} · Concern severity: ${severity}*

### Week 1–2: Foundation
- AM: Cleanser → Vitamin C serum → SPF 30+
- PM: Cleanser → Niacinamide 5% → Lightweight moisturizer
- Daily: 2L water, 7+ hours sleep

### Week 3–4: Active Introduction
- Add retinol 0.25% (2x/week, PM only) — *adjust based on skin sensitivity*
- Brow grooming to enhance natural arch
- Jawline massage technique (5 min daily)

### Lifestyle Factors
- Reduce sodium intake for under-eye puffiness
- Silk pillowcase to minimize sleep creases
- Stress management (cortisol impacts skin barrier)

---

## Clinical Note

This analysis maps **468 landmark points** across your facial topography and compares measurements against peer-group norms. Recommendations prioritize **non-surgical, evidence-based interventions** tailored to your stated concerns.

*Report generated by AuraScan AI · For demonstration purposes*
`
}
