import { formatAnswersSummary } from './onboarding'

export function buildEyeReport(eyeAnalysis, answers = {}) {
  const m = eyeAnalysis?.metrics
  if (!m) return '## Eye Analysis\n\nNo eye data available.'

  const { goals } = formatAnswersSummary(answers)

  return `## An overview of your eyes

*Computer vision analysis — MediaPipe landmarks + OpenCV-style color sampling. No LLM used.*

### Summary of your eyes

| Metric | Result |
|--------|--------|
| **Eye tilt** | ${m.eyeTilt} |
| **Eyelid exposure** | ${m.eyelidExposure} |
| **Sclera color** | ${m.scleraColor} |
| **Under-eye health** | ${m.underEyeHealth} |

### Lower eyelid curvature

- **Total bending (k):** ${m.lowerLidCurvature}
- **Typical range:** ${m.curvatureMin} – ${m.curvatureMax}
- **Assessment:** ${m.curvatureDescription}

Left eye tilt: ${m.leftTilt}° · Right eye tilt: ${m.rightTilt}° · Exposure ratio: ${m.exposureRatio}

### Explanation

${m.explanation}

---

## Personalized note

Based on your goals (*${goals}*), focus on periorbital care: SPF around the eyes, gentle caffeine or peptide serums for under-eye area, and consistent sleep to support sclera clarity.

*Report generated by AuraScan · Free CV path (MediaPipe + OpenCV) · $0 API cost*
`
}
